# Generated by Django 4.1.7 on 2023-05-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenst', '0002_student_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
